on:
    push:
      tags:
        - '*'

name: Create Release

jobs:
  release:
    name: Release to PyPI

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: []

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: lvmapi ${{ github.ref_name }}

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build source and dist
        run: |
          uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
